---
abstract: 'App to create automated letters (e.g. circular)'
author:
  - 'Jens Rehsack <rehsack@cpan.org>'
build_requires:
  App::Cmd::Tester: 0.300
  DBD::CSV: 0.31
  File::Slurp: 0
  JSON::Any: 0
  Test::More: 0.90
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Automated-Letter
provides:
  App::Automated::Letter:
    file: lib/App/Automated/Letter.pm
    version: 0.001
  App::Automated::Letter::Command::Letter:
    file: lib/App/Automated/Letter/Command/Letter.pm
    version: 0.001
requires:
  App::Cmd: 0.300
  Carp: 0
  Config::Any: 0
  File::ConfigDir: 0.003
  File::Find::Rule: 0.30
  File::ShareDir: 1.00
  LaTeX::Encode: 0.03
  Template: 2.00
  Template::Plugin::Latex: 3.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.001
